### ISSUE TITLE
Installing on windows

### ISSUE THREAD

**Issue by orelkabets** [DeV1doR/ethereumd-proxy#7]
hi there.
i'm trying to install this library on windows and i get the following error:
`` Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\or\AppData\Local\Temp\pip-build-c7lugehd\uvloop\setup.py", line 10, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')``

this library supports windows ? if so what am i doing wrong ?

**Comment by m-bo-one** [comment]
@orelkabets, I think this thing is gone from https://github.com/channelcat/sanic.
Try to remove uvloop because it does not work on windows. Or remove actual sanic and reinstall it like
[here](https://github.com/channelcat/sanic#installation)
